services:

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cleanarchitecture_api
    ports:
      - "5211:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ConnectionStrings__DefaultConnection=Server=postgres;Database=cleanArchi;Port=5432;User Id=postgres;Password=${DB_PASSWORD};
      - ConnectionStrings__Redis=redis:6379
      - Caching__Enabled=true
      - Messaging__Enabled=true
      - Messaging__RabbitMq__Host=rabbitmq
      - Messaging__RabbitMq__Username=admin
      - Messaging__RabbitMq__Password=${RABBITMQ_PASSWORD}
      - EmailSettings__Email=lordofvoid0001@gmail.com
      - EmailSettings__Password=${EMAIL_PASSWORD}
      - EmailSettings__Host=smtp.gmail.com
      - EmailSettings__DisplayName=Clean Architecture
      - EmailSettings__Port=587
      - EmailSettings__UseSSL=true
      - EmailSettings__FullName=lordofvoid0001@gmail.com
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: on-failure

  postgres:
    image: postgres:16
    container_name: cleanarchitecture_postgres
    environment:
      POSTGRES_DB: cleanArchi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "#Ab#126324!"
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: cleanarchitecture_redis
    ports:
      - "6380:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    container_name: cleanarchitecture_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: